config/routes.rb
TwilioExampleRails::Application.routes.draw do

  root :to => "pages#index"
   
  resource :sms_message, :only => [:new, :create, :incoming, :status ] do
    member do 
      get :new # form for sms_message 
      post :create # create sms_message
      post :incoming # receive message
      post :status # check message status (fail/success)
    end
  end
  
  match "/phone_call/new/:client" => "phone_calls#new" 
  
  resource :phone_call, :only => [:incoming, :new] do
    member do 
      post :incoming # incoming phone call
      get :new
    end
  end

end

app/models/phone_call.rb
require 'twilio-ruby'
require 'logger'

class PhoneCall < Object

  attr_accessor :phone_number, :twilio_number, :capability_token, :client_name

  def initialize(attributes = nil)
    @phone_number = attributes[:phone_number] unless attributes.nil?
    @twilio_number = attributes[:twilio_number] unless attributes.nil?
    @client_name = attributes[:client_name] unless attributes.nil?
    
    @account_sid = 'AC93c2fb02b30b4519a375123963434361'
    @auth_token = '5009e2c4fd8882407a4f0231f382d8db'
    
    # Get the number from twilio if the twilio number isn't passed in
    unless(@twilio_number)
      # Build the twilio client
      @client = Twilio::REST::Client.new(@account_sid, @auth_token)
    
      # Get list of numbers
      twilio_numbers_list = my_twilio_numbers
      
      # grab the first number in the list
      if (twilio_numbers_list[0] == nil)
        # You don't have a twilio number! Using the sandbox number
        # make sure to verify the number you're sending to
        @twilio_number = '+14155992671'
      else
        # Grab the first number in the list
        @twilio_number = twilio_numbers_list[0].phone_number
      end
    end
    
    # Setup capability token
    gen_capability_token
  end

private 

  def my_twilio_numbers
    numbers = @client.account.incoming_phone_numbers.list
  end
  
  def gen_capability_token
    # Create capability token class
    capability = Twilio::Util::Capability.new(@account_sid, @auth_token)
    
    # Enable outgoing calls in our app (NOT our account, note the AP in this ID)
    capability.allow_client_outgoing 'AP1b66ab4d812f4ac1b48fb4de24cc626b'
    
    # allow incoming calls to user RyanonRails
    capability.allow_client_incoming @client_name
   
    # generate the token string
    @capability_token = capability.generate
  end

end

app/models/sms_message.rb
require 'twilio-ruby'
require 'logger'

class SmsMessage < Object

  attr_accessor :phone_number, :content, :twilio_number, :available_numbers

  def initialize(attributes = nil)
    @phone_number = attributes[:phone_number] unless attributes.nil?
    @content = attributes[:content] unless attributes.nil?
    @twilio_number = attributes[:twilio_number] unless attributes.nil?
    
    @account_sid = 'AC93c2fb02b30b4519a375123963434361 '
    @auth_token = '5009e2c4fd8882407a4f0231f382d8db'
    
    # Get the number from twilio if the twilio number isn't passed in
    unless(@twilio_number)
      # Build the twilio client
      @client = Twilio::REST::Client.new(@account_sid, @auth_token)
    
      # Get list of numbers
      twilio_numbers_list = my_twilio_numbers
      
      # grab the first number in the list
      if (twilio_numbers_list[0] == nil)
        # You don't have a twilio number! Using the sandbox number
        # make sure to verify the number you're sending to
        @twilio_number = '+14155992671'
      else
        # Grab the first number in the list
        @twilio_number = twilio_numbers_list[0].phone_number
      end
      
    end
  end

  def send_msg
    # Send out a message
    @client.account.sms.messages.create(
      :from => @twilio_number,
      :to => "+1#{@phone_number}",
      :body => @content
    )
  end

  def my_twilio_numbers
    numbers = @client.account.incoming_phone_numbers.list
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    # just a placeholder for the SMS and call links
  end

end

app/controllers/phone_calls_controller.rb
class PhoneCallsController < ApplicationController
  
  def new
    if params[:client]
      # Load the client's name or whatever from the and put it as the client name
      @phone_call = PhoneCall.new({:client_name => params[:client]})
      @client = @phone_call.client_name 
    else
      # Load the client's name or whatever from the and put it as the client name
      @phone_call = PhoneCall.new({:client_name => 'NoClient'})
      @client = @phone_call.client_name 
    end

  end
  
  def incoming
    num = params[:PhoneNumber]

    # Check for number
    if /^[\d]+(\.[\d]+){0,1}$/ === num
      # dialing via number!
      # build up a response
      response = Twilio::TwiML::Response.new do |r|
        r.Dial :callerId => '+13852186888' do |d|
          d.Number num
        end
      end
    else
      # dialing via name!
      # build up a response
      response = Twilio::TwiML::Response.new do |r|
        r.Dial :callerId => '+13852186888' do |d|
          d.Client num
        end
      end
    end
    Rails.logger.debug "Reponse " + response.text
    
    render :text => response.text
    # make sure to know the diff between the number voice URL = used for incoming 
    # app voice url = used for from browser
    # (from what i can tell)
  end
  
end

app/controllers/sms_messages_controller.rb
class SmsMessagesController < ApplicationController

  before_filter :authenticate, :only => [:incoming, :status]

  def new
    @sms_message = SmsMessage.new
  end

  def create
    if params['commit'] == 'Submit Message'
       # Create sms_message
       sms_message = SmsMessage.new(params[:sms_message])
       
       # Send the Request via gem
       sms_message.send_msg
    end
    
    # Go back to send another message
    render :action => :new
  end
  
  def incoming
    # Receive a message from the user!
    message = params[:Body]
    from_number = params[:From].to_s.sub('+1', '')
    
    # Check if the message contains a specific word
    if /waffles/i.match(message)
      # Create sms_message
      sms_message = SmsMessage.new({ :phone_number => params[:From].to_s.sub('+1', ''),
                                      :content => 'I heard you like waffles...'})
                                      
      # Reply to waffles
      sms_message.send_msg
      
      # Render an empty Response
      render :text => '<?xml version="1.0" encoding="UTF-8"?><Response></Response>'
    elsif /ninja/i.match(message)
      # Reply to Ninja by building the Repsonse via xml
      render :text => '<?xml version="1.0" encoding="UTF-8"?>
                       <Response>
                        <Sms>Ninja attack!</Sms>
                       </Response>'
    end
  end
  
  def status
    
  end

  def authenticate
    # Twilio security here: http://www.twilio.com/docs/security
    # Just basic authentication for now
    authenticate_or_request_with_http_basic do |username, password|
      username == "twilio" && password == "legit"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sms_messages_helper.rb
module SmsMessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwilioExampleRails</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>
<!-- <%= debug(params) if Rails.env.development? %> -->

app/views/pages/index.html.erb
<h1>Twilio Example App</h1>
<div id="sms">
  <%= link_to 'New SMS', new_sms_message_path %>
</div>
<div id="client">
  <%= link_to 'New Phone Call - Waffle Client', :controller => "phone_calls", :action => "new", :client => "Waffles"  %>
  <br/>
  <%= link_to 'New Phone Call - Ninja Client', :controller => "phone_calls", :action => "new", :client => "Ninja"  %>

</div>

app/views/phone_calls/new.html.erb
<html>
  <head>
    <title>Ruby Twilio Client Demo!</title>
    <script type="text/javascript"
      src="http://static.twilio.com/libs/twiliojs/1.0/twilio.min.js"></script>
    <script type="text/javascript"
      src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
    <link href="http://static0.twilio.com/packages/quickstart/client.css"
      type="text/css" rel="stylesheet" />
    <script type="text/javascript">
    // This should all be put in a .js file, just here for demo purposes
      try {
        Twilio.Device.setup("<%= @phone_call.capability_token %>");
      } catch (err) {
        console.log("Adobe Flash is required to use Twilio Client.");
      }

      Twilio.Device.ready(function (device) {
        $("#log").text("Client <%= @client %> is ready");
      });
 
      Twilio.Device.error(function (error) {
        $("#log").text("Error: " + error.message);
      });
 
      Twilio.Device.disconnect(function (conn) {
        $("#log").text("Call ended");
      });
      
      Twilio.Device.incoming(function (conn) {
        $("#log").text("Incoming connection from " + conn.parameters.From);
        // accept the incoming connection and start two-way audio
        conn.accept();
      });
      
      Twilio.Device.presence(function (pres) {
        if (pres.available) {
          // create an item for the client that became available
          $("<li>", {id: pres.from, text: pres.from}).click(function () {
            $("#number").val(pres.from);
            call();
          }).prependTo("#people");
        }
        else {
          // find the item by client name and remove it
          $("#" + pres.from).remove();
        }
      });
      
      function call() {
        // get the phone number to connect the call to
        params = { "PhoneNumber": $("#number").val()};
        Twilio.Device.connect(params);
      }
      
      Twilio.Device.connect(function (conn) {
        $("#log").text("Successfully established call");
      });
      
      function hangup() {
        Twilio.Device.disconnectAll();
      }
    </script>
  </head>
  <body>
    <button class="call" onclick="call();">
      Call
    </button>
 
    <button class="hangup" onclick="hangup();">
      Hangup
    </button>
    
    <input type="text" id="number" name="number"
      placeholder="Enter a phone number to call"/>
    
    <div id="log">Loading voice app...</div>
    
    <ul id="people"/>
  </body>
</html>

app/views/sms_messages/new.html.erb
<h1>Send a new SMS Message (Twilio Request)</h1>

<%= form_for(:sms_message) do |f| %>

  <div id="phone">
    <%= f.label :phone_number %><br />
    <%= f.text_field :phone_number %>
  </div>
  
  <div id="content">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  
  <div id="submit">
    <%= submit_tag "Submit Message" %>
  </div>
  
<% end %>